server {
    listen PORT_PLACEHOLDER;
    server_name _;
    root /app/public;
    index index.php index.html;

    set $cors_origin "";
    if ($http_origin = "https://istore-chile.vercel.app") {
        set $cors_origin "https://istore-chile.vercel.app";
    }
    if ($http_origin = "http://localhost:5173") {
        set $cors_origin "http://localhost:5173";
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;

        fastcgi_hide_header 'Access-Control-Allow-Origin';
        fastcgi_hide_header 'Access-Control-Allow-Credentials';

        add_header 'Access-Control-Allow-Origin' $cors_origin always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, PATCH, DELETE, OPTIONS' always;
       add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization, X-Requested-With, Accept, X-XSRF-TOKEN, X-Session-Id' always;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }
    error_page 404 /index.php;
    location ~ /\.(?!well-known).* { deny all; }
}